language: node_js
sudo: false
node_js:
- '0.12'

branches:
  except:
    - contributions

cache:
  directories:
    - node_modules
env:
  global:
    - GH_REF: github.com/geschwendt/joshua.geschwendt.com.git
    - secure: 
      
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/64efa1a433524c5e3e25
      - https://buildtimetrend.herokuapp.com/travis
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
    
install:
  - node --version
  - npm install -g npm@2.11.3
  - npm --version
# - du -sh ./node_modules || true
  - npm install    