language: node_js
sudo: false
node_js:
- '0.12'

branches:
  except:
    - contributions

cache:
  directories:
    - node_modules
    
notifications:
    webhooks:
    - https://buildtimetrend.herokuapp.com/travis